### ISSUE TITLE
I cannot play rtmp url

### ISSUE THREAD

**Issue by lecong** [TakuSemba/RtmpPlayer#1]
Thanks for sample
But, i cannot play with url:
rtmp://sentirlite.com/live/34dad983faac98d71776fff62f4caedd?st=kY4UsS6QtX2bfIAGEayLLw&e=1523182620719

It play normal with vlc tool. Can you help me play it.

**Comment by fukemy** [comment]
I think that project is copy from other location, no helpful document, no Readme... 
Do you find out the player that working fine?

**Comment by TakuSemba** [comment]
this is just a sample app playing rtmp stream with extension-rtmp of ExoPleyer.
https://github.com/google/ExoPlayer/blob/release-v2/extensions/rtmp/README.md

This repo is nothing more than that.
There isn't much difference than using the extension yourself
